# Generated by Django 4.2.1 on 2025-04-29 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Рік випуску')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто розташування авто')),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ціна за день')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Ціна за годину')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис авто')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електро'), ('hybrid', 'Гібрид')], default='petrol', max_length=20, verbose_name='Тип пального')),
                ('transmission', models.CharField(choices=[('manual', 'Механіка'), ('automatic', 'Автомат'), ('cvt', 'Варіатор')], default='manual', max_length=20, verbose_name='Коробка передач')),
                ('seats', models.PositiveSmallIntegerField(default=4, verbose_name='Кількість місць')),
            ],
            options={
                'verbose_name': 'Авто',
                'verbose_name_plural': 'Автомобілі',
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('driver_license_series', models.CharField(max_length=10, verbose_name='Серія ПВ')),
                ('driver_license_number', models.CharField(max_length=10, verbose_name='Номер ПВ')),
                ('driver_license_tsc', models.CharField(max_length=255, verbose_name='ТСЦ')),
                ('birth_date', models.DateField(verbose_name='Дата народження власника ПВ')),
                ('selfie', models.ImageField(upload_to='users/selfies/', verbose_name='Фото для Face ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Акаунт користувача')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Фото авто')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.car', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'Фото авто',
                'verbose_name_plural': 'Фото автомобілів',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.userprofile', verbose_name='Власник'),
        ),
    ]
