# Generated by Django 4.2.1 on 2025-05-05 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_car_latitude_car_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='car',
            name='longitude',
        ),
        migrations.CreateModel(
            name='CarRentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено'), ('cancelled', 'Скасовано'), ('completed', 'Завершено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='main.car')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
