# Generated by Django 4.2.1 on 2025-05-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
    ]
