# Generated by Django 4.2.1 on 2025-05-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_message_options_message_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentalrequest',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
