# Generated by Django 4.2.1 on 2025-05-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_userprofile_unique_driver_license'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='unique_driver_license',
        ),
    ]
